# Generated by Django 4.2.1 on 2023-06-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='playlists',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='song',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='playlists',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Recommendations',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
